title: "Learn Kotlin/Native"
tagline: "A gentle introduction to Kotlin/Native"
url: http://hyde.getpoole.com
baseurl: /

author:
  name: "Tadej Slamic"
  url: http://www.tadej.me

markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate, jekyll-gist]
permalink: pretty
paginate: 5
version: 2.1.0
github:
  repo: https://github.com/poole/hyde
copyright: 'All content on this website is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">Creative Commons      Attribution-NonCommercial-NoDerivatives 4.0 International License</a>. The Kotlin logo is the property of <a href="https://www.jetbrains.com" target="_blank">JetBrains</a>. <br/> Made with ❤️ by <a href="http://www.tadej.me" target="_blank">Tadej</a>'
